### ISSUE TITLE
potential addition for the nlme-bugs project

### ISSUE THREAD

**Issue by bbolker** [r-devel/r-project-sprint-2023#13]
I just submitted this bug https://bugs.r-project.org/show_bug.cgi?id=18559 ; I suggested a fix (and pointed to discussion in a previous bug report) but didn't provide a patch.

 Could submit a PR to the [index file](https://github.com/r-devel/r-project-sprint-2023/blob/main/projects/nlme-bugs/index.Rmd) if requested.

**Comment by hturner** [comment]
A PR would be great, thanks!
