### ISSUE TITLE
Project: Facilitate Translation for Mac GUI

### ISSUE THREAD

**Issue by hturner** [r-devel/r-project-sprint-2023#31]
### Discussed in https://github.com/r-devel/r-project-sprint-2023/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **giscus[bot]** August 21, 2023</sup>
# R Project Sprint 2023 - Facilitate Translation for Mac GUI

https://contributor.r-project.org/r-project-sprint-2023/projects/mac-gui-translation/

</div>

**Comment by MichaelChirico** [comment]
Mac GUI strings are now included in Weblate, and we have a decent idea of how the process will look for submitting translations to Simon via PR, so I'm closing. Thanks all!

**Comment by hturner** [comment]
Thanks. Can anyone confirm whether task 4 "Add support for Right-to-Left languages" was achieved or if this is still on the wish list?

**Comment by MichaelChirico** [comment]
It was not! I'd missed that was a goal.

**Comment by s-u** [comment]
Unfortunately, there were not enough translations done in RTL languages during the sprint to be able to look in it. Only a few phrases were translated and none of them in the visual part so that was not enough to test. Ideally, we'd have someone do a more complete translation so we can check if/where any additional work is needed.

**Comment by hturner** [comment]
Thanks @s-u - looking more closely we have suggestions for all the Mac GUI strings in Arabic, however as they are only suggestions (made by an anonymous user that was not logged in), they are not currently being used. I am following this up to see if we can get someone to review the suggestions and accept them/add alternatives.
