### ISSUE TITLE
Project: R.app Mac GUI improvements and fixes

### ISSUE THREAD

**Issue by hturner** [r-devel/r-project-sprint-2023#39]
R.app Mac GUI improvements were discussed in https://github.com/r-devel/r-project-sprint-2023/discussions/12. The translation issue has been split into a separate project #31, adding this here in case anyone wants to pick up on any of the other issues listed during the sprint. 

<div type='discussions-op-text'>

<sup>Originally posted by **s-u** July  6, 2023</sup>
The R for Mac GUI is the most comprehensive platform-specific R GUI and has been pioneering a lot of features now present in other GUIs and commercial products, but in recent years it has not been updated to take advantage of any of the new macOS features. This idea is an umbrella for any work of the R for Mac GUI which includes:

- fixing any reported bugs related to the GUI
- improve modern features or visuals (e.g., better integration with the dark mode, modernize the setting panel)
- improve/add translations
- propose interesting features that can be implemented reasonably quickly (e.g. usablity/ergonomic features)

Please note that the work should be done on the [GitHub presence of the GUI](https://github.com/R-macos/Mac-GUI) since is it not directly tied to the R sources.</div>

**Comment by villegar** [comment]
I have "migrated" this issue to the Mac-GUI repo: https://github.com/R-macos/Mac-GUI/issues/10
