### ISSUE TITLE
Refactor `parallel` cluster code to allow packages to provide alternate/custom backends

### ISSUE THREAD

**Issue by gmbecker** [r-devel/r-project-sprint-2023#61]
Endorsed by Luke.

Currently (AFAIK) functionality is spread across the `parallel` package and some hardcoded links to functionality in the `snow` package.

- [ ] - Refactor cluster code to make use of alternate backends
- [ ] - Allow packages to register backends they implement (?)
- [ ] - API for querying which backends are available based on installed/loaded packages (??)

**Comment by shikokuchuo** [comment]
Bugzilla issue 18587 filed.
https://bugs.r-project.org/show_bug.cgi?id=18587

**Comment by ltierney** [comment]
Thanks! Let's continue working on this on bugzilla.
