### ISSUE TITLE
Further issues related to packages/CRAN

### ISSUE THREAD

**Issue by agila5** [r-devel/r-project-sprint-2023#81]
A list of issues reported on Bugzilla and related to R packages and CRAN: 

* invalid tarballs with long names: https://bugs.r-project.org/show_bug.cgi?id=17871
* requireNamespace does not behave as expected: https://bugs.r-project.org/show_bug.cgi?id=18255
* Allow users of check_packages_in_dir() to pass arguments to mclapply(): https://bugs.r-project.org/show_bug.cgi?id=18380

**Comment by aitap** [comment]
Incorporated into #34.
